# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 2 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: kostasmammas
google_analytics: Analytics Posts
title: Kostas Mammas

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Personal Blog

description: 
author:
  name: Kostas Mammas
  email: mammas_k@live.com
  github: mammask
  twitter: mammaskon
  linkedin: konstantinos-mammas
  bio: Data Scientist, Statistical Programmer
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate

theme: jekyll-theme-minimal